[package]
name = "nushift-core"
version = "0.1.0"
authors = ["David Pollack <david@pollack.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-vm = "0.23.2"
elfloader = "0.15.0"
log = "0.4.17"
num_enum = "0.5.7"
reusable-id-pool = { path = "../reusable-id-pool" }
riscy-emulator = { git = "https://github.com/michaelmelanson/riscy", tag = "0.1.1" }
# I would use the crates.io published version of riscy-isa, but we have to
# specify the same git commit to get Cargo to allow passing riscy-isa types into
# riscy-emulator.
riscy-isa = { git = "https://github.com/michaelmelanson/riscy", tag = "0.1.1" }
snafu = "0.7.1"
snafu-cli-debug = "0.1.1"
