[package]
name = "nushift"
version = "0.1.0"
authors = ["David Pollack <david@pollack.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nushift-core = { path = "../nushift-core" }

druid = "0.6.0"
